name: Build and Test

on:
  push:
    branches: [ "**" ]  # Runs on push to any branch
  pull_request:
    branches: [ "main" ]  # Runs on PRs to main
  merge_group:  # Runs on merge queue (if using merge queues)

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.gradle/kotlin-dsl
            .gradle/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Build with Gradle
        run: ./gradlew build --build-cache --parallel --continue
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false

      - name: Run tests
        run: ./gradlew test --build-cache --parallel
        env:
          GRADLE_OPTS: -Dorg.gradle.daemon=false

      - name: Run code quality checks
        run: ./gradlew detekt ktlintCheck --no-daemon --parallel
        continue-on-error: true